/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : AD2.c
**     Project     : ProcessorExpert
**     Processor   : MK53DN512ZCMD10
**     Component   : ADC
**     Version     : Component 01.688, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-12-17, 11:15, # CodeGen: 340
**     Abstract    :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : AD2
**          A/D converter                                  : ADC1
**          Sharing                                        : Disabled
**          ADC_LDD                                        : ADC_LDD
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : INT_ADC1
**            A/D interrupt priority                       : medium priority
**          A/D channels                                   : 10
**            Channel0                                     : 
**              A/D channel (pin)                          : PTB5/ENET0_1588_TMR3/FTM2_FLT0/LCD_P5/ADC1_SE11
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel1                                     : 
**              A/D channel (pin)                          : PTB6/LCD_P6/ADC1_SE12
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel2                                     : 
**              A/D channel (pin)                          : PTB7/LCD_P7/ADC1_SE13
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel3                                     : 
**              A/D channel (pin)                          : PTB10/SPI1_PCS0/UART3_RX/FTM0_FLT1/LCD_P10/ADC1_SE14
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel4                                     : 
**              A/D channel (pin)                          : PTB11/SPI1_SCK/UART3_TX/FTM0_FLT2/LCD_P11/ADC1_SE15
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel5                                     : 
**              A/D channel (pin)                          : PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/FB_AD28/I2S0_MCLK/I2S0_CLKIN/ADC1_SE17
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel6                                     : 
**              A/D channel (pin)                          : PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/FB_AD27/I2C1_SDA/ADC1_SE4a
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel7                                     : 
**              A/D channel (pin)                          : PTE1/SPI1_SOUT/UART1_RX/SDHC0_D0/FB_AD26/I2C1_SCL/ADC1_SE5a
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel8                                     : 
**              A/D channel (pin)                          : PTE2/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/FB_AD25/ADC1_SE6a
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**            Channel9                                     : 
**              A/D channel (pin)                          : PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/FB_AD24/ADC1_SE7a
**              A/D channel (pin) signal                   : 
**              Mode select                                : Single Ended
**          A/D resolution                                 : Autoselect
**          Conversion time                                : 15.666667 µs
**          Low-power mode                                 : Disabled
**          High-speed conversion mode                     : Enabled
**          Asynchro clock output                          : Disabled
**          Sample time                                    : 20 = long
**          Internal trigger                               : Enabled
**          Number of conversions                          : 1
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents    :
**         Enable               - byte AD2_Enable(void);
**         Disable              - byte AD2_Disable(void);
**         EnableEvent          - byte AD2_EnableEvent(void);
**         DisableEvent         - byte AD2_DisableEvent(void);
**         Start                - byte AD2_Start(void);
**         Stop                 - byte AD2_Stop(void);
**         Measure              - byte AD2_Measure(bool WaitForResult);
**         MeasureChan          - byte AD2_MeasureChan(bool WaitForResult, byte Channel);
**         EnableIntChanTrigger - byte AD2_EnableIntChanTrigger(byte Channel);
**         GetValue             - byte AD2_GetValue(void* Values);
**         GetChanValue         - byte AD2_GetChanValue(byte Channel, void* Value);
**         GetValue16           - byte AD2_GetValue16(word *Values);
**         Calibrate            - byte AD2_Calibrate(bool WaitForResult);
**         ConnectPin           - void AD2_ConnectPin(dword PinMask);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file AD2.c
** @version 01.00
** @brief
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
*/         
/*!
**  @addtogroup AD2_module AD2 module documentation
**  @{
*/         

/* MODULE AD2. */

#include "Events.h"
#include "AD2.h"

#ifdef __cplusplus
extern "C" {
#endif 
#define STOP            0x00U          /* STOP state           */
#define MEASURE         0x01U          /* MESURE state         */
#define CONTINUOUS      0x02U          /* CONTINUOUS state     */
#define SINGLE          0x03U          /* SINGLE state         */
#define CALIBRATING     0x04U          /* CALIBRATING state    */

static bool EnUser;                    /* Enable/Disable device */
volatile bool AD2_EnEvent;             /* Enable/Disable events */
static volatile byte SumChan;          /* Counter of measured channels */
static volatile byte ModeFlg;          /* Current state of device */
LDD_TDeviceData *AdcLdd2_DeviceDataPtr; /* Device data pointer */
/* Sample group configuration */
static LDD_ADC_TSample SampleGroup[AD2_SAMPLE_GROUP_SIZE];
static const  word Table[10] = {0x01U,0x02U,0x04U,0x08U,0x10U,0x20U,0x40U,0x80U,0x0100U,0x0200U};  /* Table of mask constants */
/* Measure multiple channels flags  */
/* Temporary buffer for converting results */
volatile word AD2_OutV[AD2_SAMPLE_GROUP_SIZE]; /* Sum of measured values */
/* Calibration in progress flag */
static volatile word OutFlg;           /* Measurement finish flag */
static volatile bool TriggerMode;      /* Trigger mode enable */

/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void ClrSumV(void)
{
  AD2_OutV[0] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[1] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[2] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[3] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[4] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[5] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[6] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[7] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[8] = 0U;                    /* Set variable for storing measured values to 0 */
  AD2_OutV[9] = 0U;                    /* Set variable for storing measured values to 0 */
}

/*
** ===================================================================
**     Method      :  AD2_HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AD2_HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    (void)AdcLdd2_Enable(AdcLdd2_DeviceDataPtr); /* Enable device */
    if (ModeFlg) {                     /* Start or stop measurement? */
      if (ModeFlg != SINGLE) {
        OutFlg = 0U;                   /* Output values aren't available */
        SumChan = 0U;                  /* Set the counter of measured channels to 0 */
        ClrSumV();                     /* Clear measured values */
        SampleGroup[0].ChannelIdx = 0U;
      }
      else {
        OutFlg &= (word)(~(word)Table[SumChan]); /* Output value isn't available */
        AD2_OutV[SumChan] = 0U;        /* Set variable for storing measured values to 0 */
        SampleGroup[0].ChannelIdx = SumChan;
      }
      (void)AdcLdd2_CreateSampleGroup(AdcLdd2_DeviceDataPtr, (LDD_ADC_TSample *)SampleGroup, 1U); /* Configure sample group */
      if (!TriggerMode) {              /* Is trigger mode enabled */
        (void)AdcLdd2_StartSingleMeasurement(AdcLdd2_DeviceDataPtr);
      } 
      else {
        (void)AdcLdd2_StartLoopTriggeredMeasurement (AdcLdd2_DeviceDataPtr);
      } 
    }
  }
  else {
    (void)AdcLdd2_Disable(AdcLdd2_DeviceDataPtr); /* Disable device */
  }
}

/*
** ===================================================================
**     Method      :  AD2_Enable (component ADC)
**     Description :
**         Enables A/D converter component. <Events> may be generated
**         (<DisableEvent>/<EnableEvent>). If possible, this method
**         switches on A/D converter device, voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD2_Enable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    return ERR_OK;                     /* If yes then set the flag "device enabled" */
  }
  EnUser = TRUE;                       /* Set the flag "device enabled" */
  AD2_HWEnDi();                        /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_Disable (component ADC)
**     Description :
**         Disables A/D converter component. No <events> will be
**         generated. If possible, this method switches off A/D
**         converter device, voltage reference, etc.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD2_Disable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_OK;                     /* If yes then OK */
  }
  EnUser = FALSE;                      /* If yes then set the flag "device disabled" */
  AD2_HWEnDi();                        /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_EnableEvent (component ADC)
**     Description :
**         Enables the <events>.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD2_EnableEvent(void)
{
  AD2_EnEvent = TRUE;                  /* Set the flag "events enabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_DisableEvent (component ADC)
**     Description :
**         Disables the <events>.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte AD2_DisableEvent(void)
{
  AD2_EnEvent = FALSE;                 /* Set the flag "events disabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_Start (component ADC)
**     Description :
**         This method starts continuous conversion on all channels
**         that are set in the component inspector. When each
**         measurement on all channels has finished the <OnEnd > event
**         may be invoked. This method is not available if the
**         <interrupt service> is disabled and the device doesn't
**         support the continuous mode. Note: If time of measurement is
**         too short and the instruction clock is too slow then the
**         conversion complete interrupt and its handler may cause a
**         system overflow.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
** ===================================================================
*/
byte AD2_Start(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = CONTINUOUS;                /* Set state of device to the continuous mode */
  TriggerMode = FALSE;                 /* Trigger mode disabled */
  AD2_HWEnDi();                        /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_Stop (component ADC)
**     Description :
**         This method stops the continuous measurement or disables
**         a trigger mode (if supported by HW), which has been
**         started by one of the following methods:
**         Version specific information not for Freescale 56800 and
**         HCS08 and HC08 and HCS12 and HCS12X derivatives ] 
**         - <Start> 
**         - EnableInt(Chan)Trigger 
**         - EnableExt(Chan)Trigger
**         The Stop method is available if one of the previously
**         mentioned methods is supported by A/D converter device
**         and is enabled to be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - No continuous measurement is
**                           running. Neither internal trigger nor
**                           external trigger have been enabled (if
**                           these are supported by HW).
** ===================================================================
*/
byte AD2_Stop(void)
{
  if (ModeFlg != CONTINUOUS) {         /* Is the device in different mode than "continuous"? */
    if (ModeFlg != SINGLE) {           /* Is device in trigger or continuous mode now? */
      return ERR_BUSY;                 /* If yes then error */
    } else if (!TriggerMode) {              /* Is device in trigger or continuous mode now? */
      return ERR_BUSY;                 /* If yes then error */
    } else {
      /* Else branch due to MISRA compliance */
    }
  }
  ModeFlg = STOP;                      /* Set state of device to the stop mode */
  (void)AdcLdd2_CancelMeasurement(AdcLdd2_DeviceDataPtr); /* Cancel measurement */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_Measure (component ADC)
**     Description :
**         This method performs one measurement on all channels that
**         are set in the component inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of a
**                           conversion. If <interrupt service> is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the <number of channels> is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the <interrupt
**                           service> is disabled and a <number of
**                           conversions> is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
** ===================================================================
*/
byte AD2_Measure(bool WaitForResult)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = MEASURE;                   /* Set state of device to the measure mode */
  TriggerMode = FALSE;                 /* Trigger mode disabled */
  AD2_HWEnDi();                        /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == MEASURE) {}      /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_MeasureChan (component ADC)
**     Description :
**         This method performs measurement on one channel. (Note: If
**         the <number of conversions> is more than one the conversion
**         of the A/D channel is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of
**                           conversion. If the <interrupt service> is
**                           disabled and at the same time a <number of
**                           conversions> is greater than 1, the
**                           WaitForResult parameter is ignored and the
**                           method waits for each result every time.
**         Channel         - Channel number. If only one
**                           channel in the component is set this
**                           parameter is ignored, because the parameter
**                           is set inside this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
**                           ERR_RANGE - Parameter "Channel" out of range
** ===================================================================
*/
/*
The definition of method:
byte AD2_MeasureChan(bool WaitForResult, byte Channel)
was optimised based on the current component setting. An appropriate macro has been defined 
in the AD1.h to maintain API compatibility.
*/
byte AD2_MeasureChan(bool WaitForResult,byte Channel)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (Channel >= 10U) {                /* Is channel number greater than or equal to 10 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = SINGLE;                    /* Set state of device to the measure mode */
  SumChan = Channel;                   /* Set required channel */
  TriggerMode = FALSE;                 /* Trigger mode disabled */
  AD2_HWEnDi();                        /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == SINGLE) {}       /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_GetValue (component ADC)
**     Description :
**         Returns the last measured values for all channels. Format
**         and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that contains
**                           the measured data. Data type is a byte, a
**                           word or an int. It depends on the supported
**                           modes, resolution, etc. of the AD converter.
**                           See the Version specific information for
**                           the current CPU in <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte AD2_GetValue(void* Values)
{
  if (OutFlg != 0x03FFU) {             /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  /* Copy measured values */
  ((AdcLdd2_TResultData *)Values)[0] = AD2_OutV[0];
  ((AdcLdd2_TResultData *)Values)[1] = AD2_OutV[1];
  ((AdcLdd2_TResultData *)Values)[2] = AD2_OutV[2];
  ((AdcLdd2_TResultData *)Values)[3] = AD2_OutV[3];
  ((AdcLdd2_TResultData *)Values)[4] = AD2_OutV[4];
  ((AdcLdd2_TResultData *)Values)[5] = AD2_OutV[5];
  ((AdcLdd2_TResultData *)Values)[6] = AD2_OutV[6];
  ((AdcLdd2_TResultData *)Values)[7] = AD2_OutV[7];
  ((AdcLdd2_TResultData *)Values)[8] = AD2_OutV[8];
  ((AdcLdd2_TResultData *)Values)[9] = AD2_OutV[9];
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AD2_GetChanValue (component ADC)
**     Description :
**         Returns the last measured value of the required channel.
**         Format and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the component is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value. Data
**                           type is a byte, a word or an int. It
**                           depends on the supported modes, resolution,
**                           etc. of the AD converter. See the Version
**                           specific information for the current CPU in
**                           <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
/*
The definition of method:
byte AD2_GetChanValue(byte Channel, void* Value)
was optimised based on the current component setting. An appropriate macro has been defined 
in the AD1.h to maintain API compatibility.
*/
byte AD2_GetChanValue(byte Channel, void* Value)
{
  if (Channel >= 10U) {                /* Is channel number greater than or equal to 10 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if ((OutFlg & Table[Channel]) == 0U) { /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  /* Copy value from temporary buffer */
  *(AdcLdd2_TResultData *)Value = AD2_OutV[Channel];
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AD2_GetValue16 (component ADC)
**     Description :
**         This method returns the last measured values of all channels
**         justified to the left. Compared with <GetValue> method this
**         method returns more accurate result if the <number of
**         conversions> is greater than 1 and <AD resolution> is less
**         than 16 bits. In addition, the user code dependency on <AD
**         resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that contains
**                           the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte AD2_GetValue16(word *Values)
{
  if (OutFlg != 0x03FFU) {             /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  Values[0] = AD2_OutV[0];             /* Save measured values to the output buffer */
  Values[1] = AD2_OutV[1];             /* Save measured values to the output buffer */
  Values[2] = AD2_OutV[2];             /* Save measured values to the output buffer */
  Values[3] = AD2_OutV[3];             /* Save measured values to the output buffer */
  Values[4] = AD2_OutV[4];             /* Save measured values to the output buffer */
  Values[5] = AD2_OutV[5];             /* Save measured values to the output buffer */
  Values[6] = AD2_OutV[6];             /* Save measured values to the output buffer */
  Values[7] = AD2_OutV[7];             /* Save measured values to the output buffer */
  Values[8] = AD2_OutV[8];             /* Save measured values to the output buffer */
  Values[9] = AD2_OutV[9];             /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AD2_Calibrate (component ADC)
**     Description :
**         This method starts self calibration process. Calibration is
**         typically used to remove the effects of the gain and offset
**         from a specific reading.
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of
**                           calibration. If the <interrupt service> is
**                           disabled, the WaitForResult parameter is
**                           ignored and the method waits for
**                           calibration result every time.
**     Returns     :
**         ---             - Error code
**                           ERR_OK - OK
**                           ERR_BUSY - A conversion is already running
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_FAILED - Calibration hasn't been
**                           finished correctly
** ===================================================================
*/
byte AD2_Calibrate(bool WaitForResult)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = CALIBRATING;               /* Set state of device to the calibration mode */
  (void)AdcLdd2_GetMeasurementCompleteStatus(AdcLdd2_DeviceDataPtr); /* Clear measurement complete status */
  (void)AdcLdd2_StartCalibration(AdcLdd2_DeviceDataPtr); /* Start calibration */
  if (!WaitForResult) {                /* If doesn't wait for result */
    return ERR_OK;                     /* then return ERR_OK, but user have to check the result of calibration e.g. by GetCalibrationStatus method */
  }
  while (!AdcLdd2_GetMeasurementCompleteStatus(AdcLdd2_DeviceDataPtr)) {}; /* Wait until calibration ends */
  if (AdcLdd2_GetCalibrationResultStatus(AdcLdd2_DeviceDataPtr) != ERR_OK) { /* If calibration failed flag is set */
    ModeFlg = STOP;                    /* Set the device to the stop mode */
    return ERR_FAILED;                 /* Return ERR_FAILED error code */
  }
  return ERR_OK;                       /* ADC device is now calibrated */
}

/*
** ===================================================================
**     Method      :  AD2_EnableIntChanTrigger (component ADC)
**     Description :
**         Enables the internal trigger mode. A conversion of one
**         required channel will be launched by internal sync pulse. If
**         the <Number of conversions> property is greater than 1, a
**         conversion will be launched more than once (by an internal
**         signal) according to <Number of conversions>. It's possible
**         to disable the trigger mode by <Stop> method.
**         [ Version specific information for other derivatives than
**         Freescale HCS12 and HCS12X ] 
**         This EnableIntChanTrigger method is available only when the
**         <Internal trigger> property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number which will be
**                           measured at internal trigger control. If
**                           only one channel in the component is set
**                           then this parameter is ignored.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_BUSY - A conversion is already running
**                           ERR_RANGE - Parameter "Channel" out of range
** ===================================================================
*/
byte AD2_EnableIntChanTrigger(byte Channel)
{
  if (Channel >= 10U) {                /* Is channel number greater than or equal to 10 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = SINGLE;                    /* Set state of device to the measure mode */
  SumChan = Channel;                   /* Set required channel */
  TriggerMode = TRUE;                  /* Trigger mode enabled */
  AD2_HWEnDi();                        /* Enable the device */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AD2_OnMeasurementComplete (component ADC)
**
**     Description :
**         The method services the conversion complete interrupt of the 
**         selected peripheral(s) and eventually invokes the beans 
**         event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AdcLdd2_OnMeasurementComplete(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  if (ModeFlg == STOP) {               /* If the driver is in STOP mode */
    return;                            /* Return from interrupt */
  }
  if (ModeFlg == CALIBRATING) {        /* If the driver is in CALIBRATING mode */
    (void)AdcLdd2_GetCalibrationResultStatus(AdcLdd2_DeviceDataPtr);
    ModeFlg = STOP;                    /* Set the device to the stop mode */
    if (AD2_EnEvent) {                 /* Are events enabled? */
      AD2_OnCalibrationEnd();          /* If yes then invoke user event */
    }
    return;                            /* Return from interrupt */
  }
  if (ModeFlg != SINGLE) {
    AdcLdd2_GetMeasuredValues(AdcLdd2_DeviceDataPtr, (LDD_TData *)&AD2_OutV[SumChan]);
    SumChan++;                         /* Increase counter of measured channels*/
    if (SumChan == 10U) {              /* Is number of measured channels equal to the number of channels used in the component? */
      SumChan = 0U;                    /* If yes then set the counter of measured channels to 0 */
      OutFlg = 0x03FFU;                /* Measured values are available */
      if (AD2_EnEvent) {               /* Are events enabled? */
        AD2_OnEnd();                   /* If yes then invoke user event */
      }
      if (ModeFlg == MEASURE) {        /* Is the device in the measure state? */
        ModeFlg = STOP;                /* Set the device to the stop mode */
        return;                        /* Return from interrupt */
      }
    }
    SampleGroup[0].ChannelIdx = SumChan; /* Start measurement of next channel */
    (void)AdcLdd2_CreateSampleGroup(AdcLdd2_DeviceDataPtr, (LDD_ADC_TSample *)SampleGroup, 1U); /* Configure sample group */
    (void)AdcLdd2_StartSingleMeasurement(AdcLdd2_DeviceDataPtr);
  }
  else {
    AdcLdd2_GetMeasuredValues(AdcLdd2_DeviceDataPtr, (LDD_TData *)&AD2_OutV[SumChan]);
    OutFlg |= Table[SumChan];          /* Value of measured channel is available */
    if (AD2_EnEvent) {                 /* Are events enabled? */
      AD2_OnEnd();                     /* If yes then invoke user event */
    }
    if (!TriggerMode) {                /* If the device is not in trigger mode */
      ModeFlg = STOP;                  /* Set the device to the stop mode */
    }
  }
}

/*
** ===================================================================
**     Method      :  AD2_ConnectPin (component ADC)
**     Description :
**         This method reconnects the requested pin associated with the
**         selected peripheral in this component. This method is
**         available only for CPU derivatives and peripherals that
**         support the runtime pin sharing with other internal on-chip
**         peripherals.
**     Parameters  :
**         NAME            - DESCRIPTION
**         PinMask         - Mask for the requested pins. The
**                           peripheral pins are reconnected according
**                           to this mask.
**                           Possible parameters:
**                           ComponentName_HIGH_VOLT_REF_PIN - High
**                           voltage reference pin
**                           ComponentName_LOW_VOLT_REF_PIN - Low
**                           voltage reference pin
**                           ComponentName_CHANNEL0_PIN - Channel 0 pin
**                           from the A/D channels list
**                           ComponentName_CHANNEL1_PIN - Channel 1 pin
**                           from the A/D channels list
**                           ComponentName_CHANNEL2_PIN - Channel 2 pin
**                           from the A/D channels list
**                           :
**                           ComponentName_CHANNEL0_NEG_PIN - Channel 0
**                           negative pin from the A/D channels list for
**                           differential mode
**                           ComponentName_CHANNEL1_NEG_PIN - Channel 1
**                           negative pin from the A/D channels list for
**                           differential mode
**                           ComponentName_CHANNEL2_NEG_PIN - Channel 2
**                           negative pin from the A/D channels list for
**                           differential mode
**                           :
**                           ComponentName_TRIGGER_PIN - Pin for
**                           external trigger
**                           
**     Returns     : Nothing
** ===================================================================
*/
void AD2_ConnectPin(dword PinMask)
{
  LDD_ADC_TPinMask PinMaskPtr;

  /* See AD2_CHANNELx_PIN definitions */
  PinMaskPtr.Channel0_31PinMask = PinMask & 0x1FFFU;
  PinMaskPtr.Channel32_63PinMask = (PinMask >> 13U) & 0x1FFFU;
  PinMaskPtr.TriggerPinMask = (uint16_t)((PinMask >> 29U) & 0x01U);
  PinMaskPtr.VoltRefPinMask = (uint8_t)((PinMask >> 30U) & 0x03U);
  AdcLdd2_ConnectPin(AdcLdd2_DeviceDataPtr, &PinMaskPtr);

}

/*
** ===================================================================
**     Method      :  AD2_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AD2_Init(void)
{
  EnUser = TRUE;                       /* Enable device */
  AD2_EnEvent = TRUE;                  /* Enable events */
  OutFlg = 0U;                         /* No measured value */
  TriggerMode = FALSE;                 /* Trigger mode disabled */
  ModeFlg = STOP;                      /* Device isn't running */
  AdcLdd2_DeviceDataPtr = AdcLdd2_Init(NULL); /* Calling init method of the inherited component */
}

/* END AD2. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
