/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : AdcLdd2.c
**     Project     : ProcessorExpert
**     Processor   : MK53DN512ZCMD10
**     Component   : ADC_LDD
**     Version     : Component 01.183, Driver 01.08, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-12-12, 14:55, # CodeGen: 341
**     Abstract    :
**         This device "ADC_LDD" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : AdcLdd2
**          A/D converter                                  : ADC1
**          Discontinuous mode                             : no
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : INT_ADC1
**            A/D interrupt priority                       : medium priority
**          DMA                                            : Disabled
**          A/D channel list                               : 10
**            Channel 0                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTB5/ENET0_1588_TMR3/FTM2_FLT0/LCD_P5/ADC1_SE11
**                  A/D channel (pin) signal               : 
**            Channel 1                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTB6/LCD_P6/ADC1_SE12
**                  A/D channel (pin) signal               : 
**            Channel 2                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTB7/LCD_P7/ADC1_SE13
**                  A/D channel (pin) signal               : 
**            Channel 3                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTB10/SPI1_PCS0/UART3_RX/FTM0_FLT1/LCD_P10/ADC1_SE14
**                  A/D channel (pin) signal               : 
**            Channel 4                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTB11/SPI1_SCK/UART3_TX/FTM0_FLT2/LCD_P11/ADC1_SE15
**                  A/D channel (pin) signal               : 
**            Channel 5                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/FB_AD28/I2S0_MCLK/I2S0_CLKIN/ADC1_SE17
**                  A/D channel (pin) signal               : 
**            Channel 6                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/FB_AD27/I2C1_SDA/ADC1_SE4a
**                  A/D channel (pin) signal               : 
**            Channel 7                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTE1/SPI1_SOUT/UART1_RX/SDHC0_D0/FB_AD26/I2C1_SCL/ADC1_SE5a
**                  A/D channel (pin) signal               : 
**            Channel 8                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTE2/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/FB_AD25/ADC1_SE6a
**                  A/D channel (pin) signal               : 
**            Channel 9                                    : 
**              Channel mode                               : Single Ended
**                Input                                    : 
**                  A/D channel (pin)                      : PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/FB_AD24/ADC1_SE7a
**                  A/D channel (pin) signal               : 
**          Static sample groups                           : Enabled
**            Sample group list                            : 1
**              Group 0                                    : 
**                Sample list                              : 1
**                  Sample 0                               : Enabled
**                    Channel index                        : 0
**          A/D resolution                                 : Autoselect
**          Low-power mode                                 : Disabled
**          High-speed conversion mode                     : Enabled
**          Asynchro clock output                          : Disabled
**          Sample time                                    : 24 clock periods
**          Number of conversions                          : 1
**          Conversion time                                : 15.666667 µs
**          ADC clock                                      : 3 MHz (333.333 ns)
**          Single conversion time - Single-ended          : 16.77 us
**          Single conversion time - Differential          : 19.77 us
**          Additional conversion time - Single-ended      : 15.666 us
**          Additional conversion time - Differential      : 18.666 us
**          Result type                                    : unsigned 16 bits, right justified
**          Trigger                                        : Enabled
**            Trigger signal list                          : 1
**              Trigger signal 0                           : Enabled
**                Trigger input                            : PDB0_CH1_TriggerA
**                Trigger input signal                     : PDB_SWTRIG
**                Trigger type                             : Internal
**                  Source component                       : PDB0
**            Trigger active state                         : Rising edge
**          Voltage reference                              : 
**            High voltage reference                       : 
**              Volt. ref. pin                             : VREFH
**              Volt. ref pin signal                       : 
**            Low voltage reference                        : 
**              Volt. ref. pin                             : VREFL
**              Volt. ref pin signal                       : 
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnMeasurementComplete                      : Enabled
**              OnError                                    : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init                          - LDD_TDeviceData* AdcLdd2_Init(LDD_TUserData *UserDataPtr);
**         Enable                        - LDD_TError AdcLdd2_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable                       - LDD_TError AdcLdd2_Disable(LDD_TDeviceData *DeviceDataPtr);
**         SetEventMask                  - LDD_TError AdcLdd2_SetEventMask(LDD_TDeviceData *DeviceDataPtr,...
**         StartSingleMeasurement        - LDD_TError AdcLdd2_StartSingleMeasurement(LDD_TDeviceData *DeviceDataPtr);
**         StartLoopTriggeredMeasurement - LDD_TError AdcLdd2_StartLoopTriggeredMeasurement(LDD_TDeviceData...
**         CancelMeasurement             - LDD_TError AdcLdd2_CancelMeasurement(LDD_TDeviceData *DeviceDataPtr);
**         GetMeasuredValues             - LDD_TError AdcLdd2_GetMeasuredValues(LDD_TDeviceData *DeviceDataPtr,...
**         CreateSampleGroup             - LDD_TError AdcLdd2_CreateSampleGroup(LDD_TDeviceData *DeviceDataPtr,...
**         GetMeasurementCompleteStatus  - bool AdcLdd2_GetMeasurementCompleteStatus(LDD_TDeviceData *DeviceDataPtr);
**         StartCalibration              - LDD_TError AdcLdd2_StartCalibration(LDD_TDeviceData *DeviceDataPtr);
**         GetCalibrationResultStatus    - LDD_TError AdcLdd2_GetCalibrationResultStatus(LDD_TDeviceData *DeviceDataPtr);
**         ConnectPin                    - LDD_TError AdcLdd2_ConnectPin(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file AdcLdd2.c
** @version 01.08
** @brief
**         This device "ADC_LDD" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
*/         
/*!
**  @addtogroup AdcLdd2_module AdcLdd2 module documentation
**  @{
*/         

/* MODULE AdcLdd2. */

#include "AD2.h"
#include "AdcLdd2.h"
/* {Default RTOS Adapter} No RTOS includes */

#ifdef __cplusplus
extern "C" { 
#endif

#define AdcLdd2_AVAILABLE_EVENTS_MASK ((LDD_TEventMask)( \
          LDD_ADC_ON_MEASUREMENT_COMPLETE))

#define AdcLdd2_INIT_EVENTS_MASK ((LDD_TEventMask)( \
          LDD_ADC_ON_MEASUREMENT_COMPLETE))

#define AdcLdd2_AVAILABLE_CHANNEL0_31_PIN_MASK (LDD_ADC_CHANNEL_0_PIN | LDD_ADC_CHANNEL_1_PIN | LDD_ADC_CHANNEL_2_PIN | LDD_ADC_CHANNEL_3_PIN | LDD_ADC_CHANNEL_4_PIN | LDD_ADC_CHANNEL_5_PIN | LDD_ADC_CHANNEL_6_PIN | LDD_ADC_CHANNEL_7_PIN | LDD_ADC_CHANNEL_8_PIN | LDD_ADC_CHANNEL_9_PIN) /*!< Mask of all allocated channel pins from 0 to 31 */
#define AdcLdd2_AVAILABLE_CHANNEL32_63_PIN_MASK 0x00U /*!< Mask of all allocated channel pins from 32 to 63 */
#define AdcLdd2_AVAILABLE_TRIGGER_PIN_MASK (LDD_ADC_TRIGGER_0_PIN) /*!< Mask of all allocated trigger pins */
#define AdcLdd2_AVAILABLE_VOLT_REF_PIN_MASK (LDD_ADC_LOW_VOLT_REF_PIN | LDD_ADC_HIGH_VOLT_REF_PIN) /*!< Mask of all allocated voltage reference pins */

static const uint8_t ChannelToPin[] = { /* Channel to pin conversion table */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x0B */
  0x4BU,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x0C */
  0x4CU,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x0D */
  0x4DU,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x0E */
  0x4EU,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x0F */
  0x4FU,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=0x11 */
  0x51U,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=4 */
  0x44U,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=5 */
  0x45U,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=6 */
  0x46U,                               /* Status and control register value */
  /* ADC1_SC1A: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,COCO=0,AIEN=1,DIFF=0,ADCH=7 */
  0x47U                                /* Status and control register value */
};

typedef struct {
  uint8_t  SampleCount;                /* Sample count */
  uint8_t  StatusControlRegVal[AdcLdd2_MAX_HW_SAMPLE_COUNT]; /* Status and control register values */
} TStaticSampleGroup;

typedef struct {
  uint8_t SampleCount;                 /* Number of samples in the last selected/created sample group */
  bool EnUser;                         /* Enable/Disable device */
  LDD_TEventMask EventMask;            /* Event mask of enabled events */
  uint8_t FirstSample;                 /* First sample of group store */
  uint8_t CompleteStatus;              /* Measurement complete status flag */
  LDD_TUserData *UserData;             /* RTOS device data structure */
} AdcLdd2_TDeviceData;                 /* Device data structure type */

typedef AdcLdd2_TDeviceData* AdcLdd2_TDeviceDataPtr ; /* Pointer to the device data structure. */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static AdcLdd2_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static AdcLdd2_TDeviceDataPtr INT_ADC1__DEFAULT_RTOS_ISRPARAM;
/*
** ===================================================================
**     Method      :  AdcLdd2_Init (component ADC_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc.
**         If the "Enable in init. code" is set to "yes" value then the
**         device is also enabled(see the description of the Enable()
**         method). In this case the Enable() method is not necessary
**         and needn't to be generated. 
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* AdcLdd2_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  AdcLdd2_TDeviceDataPtr DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* Interrupt vector(s) allocation */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_ADC1__DEFAULT_RTOS_ISRPARAM = DeviceDataPrv;
  DeviceDataPrv->SampleCount = 0U;     /* Initializing SampleCount for right access of some methods to SC1n registers before first conversion is done */
  DeviceDataPrv->EnUser = TRUE;        /* Enable device */
  DeviceDataPrv->CompleteStatus = FALSE; /* Clear measurement complete status flag */
  DeviceDataPrv->EventMask = AdcLdd2_INIT_EVENTS_MASK;
  /* SIM_SCGC3: ADC1=1 */
  SIM_SCGC3 |= SIM_SCGC3_ADC1_MASK;
  /* Interrupt vector(s) priority setting */
  /* NVICIP58: PRI58=0x80 */
  NVICIP58 = NVIC_IP_PRI58(0x80);
  /* NVICISER1: SETENA|=0x04000000 */
  NVICISER1 |= NVIC_ISER_SETENA(0x04000000);
  /* PORTB_PCR5: ISF=0,MUX=0 */
  PORTB_PCR5 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTB_PCR6: ISF=0,MUX=0 */
  PORTB_PCR6 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTB_PCR7: ISF=0,MUX=0 */
  PORTB_PCR7 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTB_PCR10: ISF=0,MUX=0 */
  PORTB_PCR10 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTB_PCR11: ISF=0,MUX=0 */
  PORTB_PCR11 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTA_PCR17: ISF=0,MUX=0 */
  PORTA_PCR17 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* ADC1_CFG2: MUXSEL=0 */
  ADC1_CFG2 &= (uint32_t)~(uint32_t)(ADC_CFG2_MUXSEL_MASK);
  /* PORTE_PCR0: ISF=0,MUX=0 */
  PORTE_PCR0 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* ADC1_CFG2: MUXSEL=0 */
  ADC1_CFG2 &= (uint32_t)~(uint32_t)(ADC_CFG2_MUXSEL_MASK);
  /* PORTE_PCR1: ISF=0,MUX=0 */
  PORTE_PCR1 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* ADC1_CFG2: MUXSEL=0 */
  ADC1_CFG2 &= (uint32_t)~(uint32_t)(ADC_CFG2_MUXSEL_MASK);
  /* PORTE_PCR2: ISF=0,MUX=0 */
  PORTE_PCR2 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* ADC1_CFG2: MUXSEL=0 */
  ADC1_CFG2 &= (uint32_t)~(uint32_t)(ADC_CFG2_MUXSEL_MASK);
  /* PORTE_PCR3: ISF=0,MUX=0 */
  PORTE_PCR3 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* SIM_SOPT7: ADC1ALTTRGEN=0 */
  SIM_SOPT7 &= (uint32_t)~(uint32_t)(SIM_SOPT7_ADC1ALTTRGEN_MASK);
  /* ADC1_CFG1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ADLPC=0,ADIV=3,ADLSMP=1,MODE=3,ADICLK=1 */
  ADC1_CFG1 = ADC_CFG1_ADIV(0x03) |
              ADC_CFG1_ADLSMP_MASK |
              ADC_CFG1_MODE(0x03) |
              ADC_CFG1_ADICLK(0x01);
  /* ADC1_CFG2: ADACKEN=0,ADHSC=1,ADLSTS=0 */
  ADC1_CFG2 = (uint32_t)((ADC1_CFG2 & (uint32_t)~(uint32_t)(
               ADC_CFG2_ADACKEN_MASK |
               ADC_CFG2_ADLSTS(0x03)
              )) | (uint32_t)(
               ADC_CFG2_ADHSC_MASK
              ));
  /* ADC1_SC2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ADACT=0,ADTRG=0,ACFE=0,ACFGT=0,ACREN=0,DMAEN=0,REFSEL=0 */
  ADC1_SC2 = ADC_SC2_REFSEL(0x00);
  /* ADC1_SC3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CAL=0,CALF=1,??=0,??=0,ADCO=0,AVGE=0,AVGS=0 */
  ADC1_SC3 = (ADC_SC3_CALF_MASK | ADC_SC3_AVGS(0x00));
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_AdcLdd2_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv); /* Return pointer to the data data structure */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_Enable (component ADC_LDD)
*/
/*!
**     @brief
**         Enables ADC device. If possible, this method switches on A/D
**         converter device, voltage reference, etc. This method is
**         intended to be used together with [Disable()] method to
**         temporary switch On/Off the device after the device is
**         initialized. This method is required if the [Enabled in init.
**         code] property is set to "no" value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
*/
/* ===================================================================*/
LDD_TError AdcLdd2_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser = TRUE; /* Set the flag "device enabled" */
  return ERR_OK;                       /* If yes then set the flag "device enabled" */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_Disable (component ADC_LDD)
*/
/*!
**     @brief
**         Disables the ADC device. If possible, this method switches
**         off A/D converter device, voltage reference, etc. (for
**         example to avoid power consumption and possible interference).
**         When the device is disabled, some component methods should
**         not be called. If so, error ERR_DISABLED is reported. This
**         method is intended to be used together with [Enable()]
**         method to temporary switch On/Off the device after the
**         device is initialized. This method is not required. The
**         [Deinit()] method can be used to switch off and uninstall
**         the device.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
*/
/* ===================================================================*/
LDD_TError AdcLdd2_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser = FALSE; /* Set the flag "device disabled" */
  ADC_PDD_SetConversionTriggerType(ADC1_BASE_PTR, ADC_PDD_SW_TRIGGER); /* Select SW triggering */
  ADC_PDD_WriteStatusControl1Reg(ADC1_BASE_PTR, 0U, 0x1FU); /* Disable device */
  return ERR_OK;                       /* If yes then set the flag "device enabled" */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_SetEventMask (component ADC_LDD)
*/
/*!
**     @brief
**         Enables/disables event(s). The events contained within the
**         mask are enabled. Events not contained within the mask are
**         disabled. The component event masks are defined in the
**         PE_Types.h file. Note: At least one [event] must be
**         generated to generate this method. Events that are not
**         generated are not handled by this method. Pair method to
**         GetEventMask().
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         EventMask       - Event mask
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
**                           ERR_PARAM_MASK - Event mask is not valid
**                           (requested event is not defined by this
**                           component or event is generated)
*/
/* ===================================================================*/
LDD_TError AdcLdd2_SetEventMask(LDD_TDeviceData *DeviceDataPtr, LDD_TEventMask EventMask)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  /* Event mask test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((EventMask & (LDD_TEventMask)(~(LDD_TEventMask)(AdcLdd2_AVAILABLE_EVENTS_MASK))) != 0U) { /* Is the parameter EventMask within an expected range? */
    return ERR_PARAM_MASK;             /* If no then error. */
  }
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EventMask = EventMask; /* Set the new event mask. */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_StartSingleMeasurement (component ADC_LDD)
*/
/*!
**     @brief
**         This method starts one measurement of the selected group of
**         samples and exits immediately. This is ADC SW trigger method.
**         The group of samples for measurement is specified by
**         preceding call to [SelectSampleGroup()] or
**         [CreateSampleGroup] method. 
**         DMA disabled: The [OnMeasurementComplete() ] event is
**         invoked after the measurement is done and if the event is
**         enabled. Results of the measurement can be read by the
**         [GetMeasuredValues()] method. 
**         DMA enabled: DMA request from configured ADC is enabled
**         automatically. The [OnMeasurementComplete() ] event is
**         invoked after the requested number of results are
**         transferred to destination buffer by DMA and if the event is
**         enabled. [GetMeasuredValues()] method is not available if
**         DMA mode is enabled. If the DMA transfer was completed
**         before and DMA is not recofingured, DMA error can occur. See
**         also [SetBuffer()] method. 
**         The state of the measurement can be also polled by the
**         [GetMeasurementCompleteStatus()] method. The [Discontinuous
**         mode] doesn't support this method.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
**                           ERR_BUSY - A measurement is in progress 
*/
/* ===================================================================*/
LDD_TError AdcLdd2_StartSingleMeasurement(LDD_TDeviceData *DeviceDataPtr)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ADC_PDD_GetConversionTriggerType(ADC1_BASE_PTR) != 0U) { /* Is HW loop measurement in progress? */
    return ERR_BUSY;                   /* Yes, return BUSY */
  }
  if (ADC_PDD_GetConversionActiveFlag(ADC1_BASE_PTR) != 0U) { /* Last measurement still pending? */
    return ERR_BUSY;                   /* Yes, return ERR_BUSY */
  }
  ADC_PDD_SetContinuousMode(ADC1_BASE_PTR, ADC_PDD_ONE_CONVERSION); /* Set one conversion mode */
  ADC_PDD_SetConversionTriggerType(ADC1_BASE_PTR, ADC_PDD_SW_TRIGGER); /* Select SW triggering */
  ADC_PDD_WriteStatusControl1Reg(ADC1_BASE_PTR, 0U, ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->FirstSample); /* Set sample 0 and start conversion */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_StartLoopTriggeredMeasurement (component ADC_LDD)
*/
/*!
**     @brief
**         This method prepares recurring measurement of the selected
**         group of samples and exits immediately. Multiple
**         measurements of the selected sample group are done, but each
**         measurement of the sample group is not started until the
**         trigger comes. Beware of trigger overflow (next trigger
**         comes before the previous measurement is done). This is ADC
**         HW trigger method. 
**         The group of samples for measurement is specified by
**         preceding call to [SelectSampleGroup()] or
**         [CreateSampleGroup] method. 
**         DMA disabled: The [OnMeasurementComplete()] event is invoked
**         after the each measurement is done and the event is enabled.
**         Results of the measurement can be read by the
**         [GetMeasuredValues()] method. 
**         DMA enabled: DMA request from configured ADC is enabled
**         automatically. The [OnMeasurementComplete() ] event is
**         invoked after the requested number of results are
**         transferred to destination buffer by DMA and the event is
**         enabled. When DMA transfer is finished, DMA request is
**         automatically disabled by HW, but ADC loop mode is not
**         stopped. In order to start new loop measurement with DMA,
**         DMA must be reconfigured by [SetBuffer()] method.
**         [GetMeasuredValues()] method is not available if DMA mode is
**         enabled. 
**         The state of the measurement can be also polled by the
**         [GetMeasurementCompleteStatus()] method.This method is
**         available only if HW supports triggered measurement and
**         [Trigger] is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
**                           ERR_BUSY - Measurement is in progress 
*/
/* ===================================================================*/
LDD_TError AdcLdd2_StartLoopTriggeredMeasurement(LDD_TDeviceData *DeviceDataPtr)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ADC_PDD_GetConversionTriggerType(ADC1_BASE_PTR) != 0U) { /* Is HW loop measurement in progress? */
    return ERR_BUSY;                   /* Yes, return BUSY */
  }
  if (ADC_PDD_GetConversionActiveFlag(ADC1_BASE_PTR) != 0U) { /* Last measurement still pending? */
    return ERR_BUSY;                   /* Yes, return ERR_BUSY */
  }
  ADC_PDD_SetContinuousMode(ADC1_BASE_PTR, ADC_PDD_ONE_CONVERSION); /* Set one conversion mode */
  ADC_PDD_SetConversionTriggerType(ADC1_BASE_PTR, ADC_PDD_HW_TRIGGER); /* Select HW triggering */
  ADC_PDD_WriteStatusControl1Reg(ADC1_BASE_PTR, 0U, ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->FirstSample); /* Set sample 0 */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_CancelMeasurement (component ADC_LDD)
*/
/*!
**     @brief
**         This method cancels the measurement in progress. Typically
**         the OnMeasurementComplete() event is not invoked for
**         cancelled measurement. If DMA mode is enabled, DMA request
**         from ADC is disabled and DMA transfer is cancelled. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
*/
/* ===================================================================*/
LDD_TError AdcLdd2_CancelMeasurement(LDD_TDeviceData *DeviceDataPtr)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  ADC_PDD_SetConversionTriggerType(ADC1_BASE_PTR, ADC_PDD_SW_TRIGGER); /* Select SW triggering */
  ADC_PDD_WriteStatusControl1Reg(ADC1_BASE_PTR, 0U, 0x1FU); /* Disable device - A */
  
  return ERR_OK;                       /* If yes then set the flag "device enabled" */  
}

/*
** ===================================================================
**     Method      :  AdcLdd2_CreateSampleGroup (component ADC_LDD)
*/
/*!
**     @brief
**         This method prepares HW for next measurement according to
**         array of samples defined during run-time. The array of
**         samples should be prepared prior to calling this method.
**         Pointer to the array is passed into this method in parameter
**         SampleGroupPtr. The number of samples is defined by
**         parameter SampleCount. Once any group is prepared, the
**         measurement can be started multiple times. Note: This method
**         works only with the sample groups defined during run-time.
**         For design-time defined groups use [SelectSampleGroup()]
**         method.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         SampleGroupPtr  - Pointer to the
**                           sample definition array. This array can be
**                           released as soon as the method ends.
**     @param
**         SampleCount     - Number of items in the
**                           sample definition array. Must be less than
**                           or equal to
**                           ComponentName_MAX_HW_SAMPLE_COUNT.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
**                           ERR_PARAM_INDEX - Channel index in
**                           SampleGroup structure is out of range
**                           ERR_PARAM_SAMPLE_COUNT - SampleCount
**                           variable value is out of range
**                           ERR_BUSY - Measurement is in progress 
*/
/* ===================================================================*/
LDD_TError AdcLdd2_CreateSampleGroup(LDD_TDeviceData *DeviceDataPtr, LDD_ADC_TSample *SampleGroupPtr, uint8_t SampleCount)
{
  AdcLdd2_TDeviceDataPtr DeviceDataPrv = (AdcLdd2_TDeviceDataPtr)DeviceDataPtr;

  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  /* Sample count test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((SampleCount > AdcLdd2_MAX_HW_SAMPLE_COUNT) || (SampleCount == 0U)) { /* Is number of sample greater then supported by the HW? */
    return ERR_PARAM_SAMPLE_COUNT;     /* Yes, return ERR_PARAM_SAMPLE_COUNT */
  }
  if (ADC_PDD_GetConversionTriggerType(ADC1_BASE_PTR) != 0U) { /* Is HW loop measurement in progress? */
    return ERR_BUSY;                   /* Yes, return BUSY */
  }
  if (ADC_PDD_GetConversionActiveFlag(ADC1_BASE_PTR) != 0U) { /* Last measurement still pending? */
    return ERR_BUSY;                   /* Yes, return ERR_BUSY */
  }
  DeviceDataPrv->SampleCount = SampleCount; /* Remember sample count */
  /* Channel index test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if (SampleGroupPtr[0].ChannelIdx >= AdcLdd2_CHANNEL_COUNT) { /* Is channel index out of range? */
    return ERR_PARAM_INDEX;            /* Yes, return ERR_PARAM_INDEX */
  }
  DeviceDataPrv->FirstSample = (ChannelToPin[SampleGroupPtr[0].ChannelIdx]) | (uint8_t)(LDD_ADC_ON_MEASUREMENT_COMPLETE); /* Remember first sample */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_GetMeasuredValues (component ADC_LDD)
*/
/*!
**     @brief
**         This method copies results of the last measurement to the
**         user supplied buffer. Data size depends on the size of
**         measured sample group (see [SelectSampleGroup()] or
**         [CreateSampleGroup()] method). Data representation is
**         defined by the [Result type] property. Typically this method
**         is called from [OnMeasurementComplete] event to get results
**         of the last measurement. This method is not available if DMA
**         is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         BufferPtr       - Pointer to the start of the
**                           buffer for new results. Count of stored
**                           measured values equals to the count of the
**                           samples in the active sample group. It is
**                           in the user responsibility to provide
**                           buffer with appropriate size.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
*/
/* ===================================================================*/
LDD_TError AdcLdd2_GetMeasuredValues(LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr)
{
  uint8_t Sample;
  AdcLdd2_TResultData *pBuffer = (AdcLdd2_TResultData *)BufferPtr;

  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  /* Copy values from result registers defined in the active sample
     group to the user supplied buffer */
  for (Sample = 0U; Sample < ((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->SampleCount; Sample++) {
    pBuffer[Sample] =(uint16_t)(ADC_PDD_GetResultValueRaw(ADC1_BASE_PTR, Sample));
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_GetMeasurementCompleteStatus (component ADC_LDD)
*/
/*!
**     @brief
**         Returns whether the measurement is done and the results can
**         be read by the user. It can be used to poll the state of
**         measurement if [Interrupt service/event] is disabled or if
**         [OnMeasurementComplete] event is disabled by the
**         [SetEventMask()] methods.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code
**                           true - Measurement is done
**                           false - Measurement is in progress
*/
/* ===================================================================*/
bool AdcLdd2_GetMeasurementCompleteStatus(LDD_TDeviceData *DeviceDataPtr)
{
  uint8_t Status;
  AdcLdd2_TDeviceDataPtr DeviceDataPrv = (AdcLdd2_TDeviceDataPtr)DeviceDataPtr;
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  Status = DeviceDataPrv->CompleteStatus; /* Save flag for return */
  DeviceDataPrv->CompleteStatus = FALSE; /* Clear measurement complete status flag */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  return (bool)((Status)? TRUE : FALSE); /* Return saved status */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_StartCalibration (component ADC_LDD)
*/
/*!
**     @brief
**         This method starts self calibration process. Calibration is
**         typically used to remove the effects of the gain and offset
**         from a specific reading.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_DISABLED - Component is disabled
**                           ERR_BUSY - A conversion is already running 
*/
/* ===================================================================*/
LDD_TError AdcLdd2_StartCalibration(LDD_TDeviceData *DeviceDataPtr)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((AdcLdd2_TDeviceDataPtr)DeviceDataPtr)->EnUser) { /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ADC_PDD_GetConversionTriggerType(ADC1_BASE_PTR) != 0U) { /* Is HW loop measurement in progress? */
    return ERR_BUSY;                   /* Yes, return BUSY */
  }
  if (ADC_PDD_GetConversionActiveFlag(ADC1_BASE_PTR) != 0U) { /* Last measurement still pending? */
    return ERR_BUSY;                   /* Yes, return ERR_BUSY */
  }
  ADC_PDD_SetConversionTriggerType(ADC1_BASE_PTR, ADC_PDD_SW_TRIGGER); /* Select SW triggering */
  ADC_PDD_WriteStatusControl1Reg(ADC1_BASE_PTR, 0U, ADC_PDD_MODULE_DISABLED | ((uint32_t)LDD_ADC_ON_MEASUREMENT_COMPLETE)); /* Set Control 1 register */
  ADC_PDD_StartCalibration(ADC1_BASE_PTR); /* Start calibration */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AdcLdd2_GetCalibrationResultStatus (component ADC_LDD)
*/
/*!
**     @brief
**         This method should be used for check the last calibration
**         result. If calibration completed normally the method finish
**         calibration process by writing gain calibration values.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code
**                           ERR_OK - OK 
**                           ERR_FAILED - Last calibration hasn't been
**                           finished correctly
*/
/* ===================================================================*/
LDD_TError AdcLdd2_GetCalibrationResultStatus(LDD_TDeviceData *DeviceDataPtr)
{
  uint32_t GainValue;

  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if (ADC_PDD_GetCalibrationFailedStatusFlag(ADC1_BASE_PTR)) {
    return ERR_FAILED;
  }
  /* If calibration is successfully passed place calibrated value into gain registers */
  /* Cumulated gradually because of undefined behavior: the order of volatile accesses is undefined in this statement */
  GainValue = ADC_PDD_GetPlus0CalibrationValue(ADC1_BASE_PTR); /* Find plus gain value */
  GainValue += ADC_PDD_GetPlus1CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetPlus2CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetPlus3CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetPlus4CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetPlusSCalibrationValue(ADC1_BASE_PTR);
  GainValue = (GainValue >> 1U) | 0x8000U;
  ADC_PDD_SetPlusGainValue(ADC1_BASE_PTR,GainValue); /* Set plus gain value */
  GainValue = ADC_PDD_GetMinus0CalibrationValue(ADC1_BASE_PTR); /* Find minus gain value */
  GainValue += ADC_PDD_GetMinus1CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetMinus2CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetMinus3CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetMinus4CalibrationValue(ADC1_BASE_PTR);
  GainValue += ADC_PDD_GetMinusSCalibrationValue(ADC1_BASE_PTR);
  GainValue =  (GainValue >> 1U) | 0x8000U;
  ADC_PDD_SetMinusGainValue(ADC1_BASE_PTR,GainValue); /* Set minus gain value */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AdcLdd2_ConnectPin (component ADC_LDD)
*/
/*!
**     @brief
**         This method reconnects the requested pin associated with the
**         selected peripheral in this component. This method is
**         available only for CPU derivatives and peripherals that
**         support the runtime pin sharing with other internal on-chip
**         peripherals.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         PinMaskPtr      - Pointer to the [structure of
**                           bit masks] for the requested pins. The
**                           peripheral pins are reconnected according
**                           to this structure.
**                           Possible parameters:
**                           LDD_ADC_CHANNEL_X_PIN - Channel X pin (pair
**                           in differential mode) from the A/D channels
**                           list
**                           LDD_ADC_TRIGGER_X_PIN - External trigger
**                           pin
**                           LDD_ADC_HIGH_VOLT_REF_PIN - High voltage
**                           reference pin (for converter A on 56800
**                           family)
**                           LDD_ADC_LOW_VOLT_REF_PIN - Low voltage
**                           reference pin (for converter A on 56800
**                           family)
**                           
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The device doesn't work in the
**                           active clock configuration
**                           ERR_PARAM_MASK - A pin mask in the pin mask
**                           structure is not valid (requested event is
**                           not defined by this component or event is
**                           generated)
*/
/* ===================================================================*/
LDD_TError AdcLdd2_ConnectPin(LDD_TDeviceData *DeviceDataPtr, LDD_ADC_TPinMask *PinMaskPtr)
{
  uint32_t Mask;                       /* Temporary pin mask */

  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  /* Pin mask test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((PinMaskPtr->Channel0_31PinMask & ((uint32_t)~((uint32_t)AdcLdd2_AVAILABLE_CHANNEL0_31_PIN_MASK))) != 0U) {
    return ERR_PARAM_MASK;
  }
  if ((PinMaskPtr->Channel32_63PinMask & ((uint32_t)~((uint32_t)AdcLdd2_AVAILABLE_CHANNEL32_63_PIN_MASK))) != 0U) {
    return ERR_PARAM_MASK;
  }
  if ((PinMaskPtr->TriggerPinMask & ((uint16_t)~((uint16_t)AdcLdd2_AVAILABLE_TRIGGER_PIN_MASK))) != 0U) {
    return ERR_PARAM_MASK;
  }
  if ((PinMaskPtr->VoltRefPinMask & ((uint8_t)~((uint8_t)AdcLdd2_AVAILABLE_VOLT_REF_PIN_MASK))) != 0U) {
    return ERR_PARAM_MASK;
  }
  Mask = PinMaskPtr->Channel0_31PinMask;
  if ((Mask & LDD_ADC_CHANNEL_0_PIN) != 0U) {
    clrReg32Bits(PORTB_PCR5, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_1_PIN) != 0U) {
    clrReg32Bits(PORTB_PCR6, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_2_PIN) != 0U) {
    clrReg32Bits(PORTB_PCR7, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_3_PIN) != 0U) {
    clrReg32Bits(PORTB_PCR10, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_4_PIN) != 0U) {
    clrReg32Bits(PORTB_PCR11, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_5_PIN) != 0U) {
    clrReg32Bits(PORTA_PCR17, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_6_PIN) != 0U) {
    clrReg32Bits(ADC1_CFG2, 0x10U);    /* MUXSEL=0x00U */
    clrReg32Bits(PORTE_PCR0, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_7_PIN) != 0U) {
    clrReg32Bits(ADC1_CFG2, 0x10U);    /* MUXSEL=0x00U */
    clrReg32Bits(PORTE_PCR1, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_8_PIN) != 0U) {
    clrReg32Bits(ADC1_CFG2, 0x10U);    /* MUXSEL=0x00U */
    clrReg32Bits(PORTE_PCR2, 0x01000700U); /* MUX=0x00U */
  }
  if ((Mask & LDD_ADC_CHANNEL_9_PIN) != 0U) {
    clrReg32Bits(ADC1_CFG2, 0x10U);    /* MUXSEL=0x00U */
    clrReg32Bits(PORTE_PCR3, 0x01000700U); /* MUX=0x00U */
  }
  Mask = PinMaskPtr->TriggerPinMask;
  if ((Mask & LDD_ADC_TRIGGER_0_PIN) != 0U) {
    clrReg32Bits(SIM_SOPT7, 0x8000U);  /* ADC1ALTTRGEN=0x00U */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AdcLdd2_MeasurementCompleteInterrupt (component ADC_LDD)
**
**     Description :
**         Measurement complete interrupt handler
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(AdcLdd2_MeasurementCompleteInterrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  AdcLdd2_TDeviceDataPtr DeviceDataPrv = INT_ADC1__DEFAULT_RTOS_ISRPARAM;
  DeviceDataPrv->CompleteStatus = TRUE; /* Set measurement complete status flag */
  if ((DeviceDataPrv->EventMask & LDD_ADC_ON_MEASUREMENT_COMPLETE) != 0U) {
    AdcLdd2_OnMeasurementComplete(DeviceDataPrv->UserData);
  }
  (void)ADC_PDD_GetResultValueRaw(ADC1_BASE_PTR, 0U); /* Clear conversion complete flag */
}

/* END AdcLdd2. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
