/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PDB0.h
**     Project     : ProcessorExpert
**     Processor   : MK53DN512ZCMD10
**     Component   : Init_PDB
**     Version     : Component 01.004, Driver 01.04, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-12-17, 02:13, # CodeGen: 334
**     Abstract    :
**          This file implements the PDB (PDB0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PDB0
**          Device                                         : PDB0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Prescaler                                  : divide by 32
**              Divider                                    : divide by 20
**              Counter frequency                          : 75 kHz
**              Modulus                                    : 37
**              Counter period                             : 493.333 us
**              Continuous mode enable                     : Continuous
**              Interrupt delay value                      : 0
**              Interrupt delay                            : 0.000 us
**            Load Mode                                    : Immediate
**          Channels                                       : 
**            Channel triggers                             : 
**              Channel 0 trigger                          : 
**                Trigger A                                : 
**                  Trigger A enable                       : Disabled
**                  Output select A                        : bypassed
**                  Back to Back                           : Disabled
**                  Trigger delay A value                  : 0
**                  Trigger A delay                        : 0.000 us
**                Trigger B                                : 
**                  Trigger B enable                       : Disabled
**                  Output select B                        : bypassed
**                  Back to Back                           : Disabled
**                  Trigger delay B value                  : 0
**                  Trigger B delay                        : 0.000 us
**              Channel 1 trigger                          : 
**                Trigger A                                : 
**                  Trigger A enable                       : Enabled
**                  Output select A                        : Delay only
**                  Back to Back                           : Disabled
**                  Trigger delay A value                  : 0
**                  Trigger A delay                        : 0.000 us
**                Trigger B                                : 
**                  Trigger B enable                       : Disabled
**                  Output select B                        : bypassed
**                  Back to Back                           : Disabled
**                  Trigger delay B value                  : 0
**                  Trigger B delay                        : 0.000 us
**            Channel for DAC                              : 
**              Trigger to DAC0                            : 
**                Trigger Output                           : Disabled
**                External trigger input enable            : Disabled
**                Trigger interval value                   : 0
**                Trigger interval time                    : 13.333 us
**              Trigger to DAC1                            : 
**                Trigger Output                           : Disabled
**                External trigger input enable            : Disabled
**                Trigger interval value                   : 0
**                Trigger interval time                    : 13.333 us
**            Pulse outs                                   : 
**              Pulse out 0                                : 
**                Pulse output                             : Disabled
**                Delay 1 value                            : 0
**                Delay of rising edge                     : 0.000 us
**                Delay 2 value                            : 0
**                Delay of falling edge                    : 0.000 us
**          Pins/Signals                                   : 
**            Input trigger select                         : PDB_SWTRIG
**            Input trigger select signal                  : 
**          Interrupts/DMA                                 : 
**            Interrupt                                    : INT_PDB0
**            Interrupt request                            : Enabled
**            Interrupt priority                           : 0 (Highest)
**            ISR name                                     : PDB0_ISR
**            PDB interrupt                                : Enabled
**            Sequence error interrupt                     : Disabled
**            DMA request                                  : Disabled
**          Initialization                                 : 
**            Load OK                                      : yes
**            Enable PDB                                   : yes
**            Call Init method                             : yes
**     Contents    :
**         Init - void PDB0_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PDB0.h
** @version 01.04
** @brief
**          This file implements the PDB (PDB0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PDB0_module PDB0 module documentation
**  @{
*/         

#ifndef PDB0_H_
#define PDB0_H_

/* MODULE PDB0. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/* Peripheral base address parameter */
#define PDB0_DEVICE PDB0_BASE_PTR


/*
** ===================================================================
**     Method      :  PDB0_Init (component Init_PDB)
**     Description :
**         This method initializes registers of the PDB module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PDB0_Init(void);
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see PDB0.c file for more information).
** ===================================================================
*/
PE_ISR(PDB0_ISR);


/* END PDB0. */
#endif /* #ifndef __PDB0_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
